release:
  disable: false
  github: {}
builds:
    - env:
        - CGO_ENABLED=0
      goarch:
       - amd64
      goos:
       - windows
       - linux
       - darwin
nfpm:
  formats:
    - deb
    - rpm
  license: Apache License 2.0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
