services:
  - docker

sudo: required
env:
  - GO111MODULE=on

language: go
go:
  - 1.11.x

script:
  - sudo apt-get install -y rpmbuild
before_install:
  - go mod download

deploy:
  provider: script
  script: bash scripts/release.sh
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
